# -*- coding: utf-8 -*-
"""headbrainsize.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vo1Spd-TCHHH5A0AcZnW2Vd-akSISgy0
"""

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

downloaded = drive.CreateFile({'id':'1P4DXhuQY4xWr0AFejK_zqpEF8JtMqhta'}) 
downloaded.GetContentFile('headbrain.csv')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize']=(18.0,5.0)
data=pd.read_csv('headbrain.csv');
print(data.shape)
data.head()

x=data['Head Size(cm^3)'].values
y=data['Brain Weight(grams)'].values

mean_x=np.mean(x)
mean_y=np.mean(y)
m=len(x)
num=0
den=0
for i in range(m):
  num += (x[i]- mean_x)*(y[i]-mean_y)
  den += (x[i]- mean_x)**2
b1=num/den
b0=mean_y-(b1*mean_x)
print(b1,b0)

max_x=np.max(x) + 100
min_x=np.min(x) - 100
a=np.linspace(max_x,min_x,1000)
b=b0+b1*x
plt.plot(a,b,color='#58b790' , label='regression line')
plt.scatter(x,y,color='#ef5423', label='scatter plot')
plt.xlabel('Head Size in cm3')
plt.ylabel('Brain Weight in grams')
plt.legend()
plt.show()